shop_emzs:
  image: dnhsoft/shopware:5.6.0
  links:
   - db_emz
  volumes:
   - "./../plugins:/shopware/custom/plugins"
  ports:
   - "8000:80"
  environment:
   SWDB_HOST: db_emz
   SWDB_DATABASE: stream
  env_file:
   - shop-variables-local.env


db_emz:
  image: tutum/mysql:5.6
  environment:
   MYSQL_USER: root
   MYSQL_PASS: 123456

pma_emz:
  image: dnhsoft/phpmyadmin:4.6.4
  links:
   - db_emz
  ports:
   - "8001:80"
  environment:
   DBHOST: db_emz
